### ISSUE TITLE
Reproduce results for hotel review reconstruction

### ISSUE THREAD

**Issue by Hexiang-Hu** [dreasysnail/textCNN_public#1]
Hi, 

I read through your paper on ArXiv and was fascinated by the reconstruction result of your model. However, I found out that directly running the current version of demo code could not reproduce your claimed result. (Current BLEU2 is ~25, far from ~94 as in the paper)

I wonder if there is some special settings for your experiment in the paper. It would be very helpful if you can kindly provide more instructions on how to run the code correctly. Thanks!

Best,

**Comment by dreasysnail** [comment]
Hi,

Thank you for the interest to our model. Yes there is something wrong with our previous code. I have updated (and reruned) the open sourced code on Github, and hopeful you are able to run the experiment this time. I have also uploaded a sample output file, which print out output results and validation BLEU score. Let me know if you are still unable to achieve the results.

**Comment by Hexiang-Hu** [comment]
Thank you so much! 

I think now things looks correct. 

Best,
