### ISSUE TITLE
Replicating the semi-supervised experiments

### ISSUE THREAD

**Issue by ajaynagesh** [dreasysnail/textCNN_public#2]
I was unable to locate the code to replicate the semi-supervised experiments (on the 3 datasets - Yelp, DBPedia and Y! Answers). Could you please point out how to run the same. 

Also Could you please let me know how the datasets were pre-processed to obtain the statistics you mention in the SM, Table 7. (especially Vocabulary)

Thanks!

**Comment by ajaynagesh** [comment]
@dreasysnail Could you please let me know about the semi-supervised experiments. Thanks!

**Comment by dreasysnail** [comment]
Thanks for your interest, and I am sorry for the delay. The code will be released by the end of this month.
